[tool.poetry]
name = "backend"
version = "0.1.0"
description = "The API for Children AI Assistant"
authors = ["qicaisheng <qicaisheng@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
